version: '3.8'

networks:
  backend-network:
    name: backend-network
    driver: bridge

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: upload_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - backend-network

  upload-service:
    build:
      context: ./upload-service
    container_name: upload-service
    privileged: true
    ports:
      - "8081:8081"
    environment:
      FILE_UPLOAD_PATH: /uploads
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/upload_service
      SPRING_JDBC_URL: jdbc:postgresql://postgres:5432/upload_service
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_QUEUE: file-processing-queue
      SPRING_RABBITMQ_QUEUE_PROCESSED: file-processed-queue
      SPRING_RABBITMQ_QUEUE_NOTIFICATION_FAILURE: notification-failures
      SPRING_RABBITMQ_FILE_PROCESSED_TOPIC_EXCHANGE: file.processed.topic
    volumes:
      - shared_uploads:/uploads
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend-network

  processing-service:
    build:
      context: ./processing-service
    container_name: processing-service
    privileged: true
    ports:
      - "8082:8082"
    environment:
      FILE_UPLOAD_PATH: /uploads
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_QUEUE: file-processing-queue
      SPRING_RABBITMQ_QUEUE_PROCESSED: file-processed-queue
      SPRING_RABBITMQ_NOTIFICATION: notification-queue
      SPRING_RABBITMQ_QUEUE_NOTIFICATION_FAILURE: notification-failures
      SPRING_RABBITMQ_FILE_PROCESSED_TOPIC_EXCHANGE: file.processed.topic
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
      MINIO_BUCKET_NAME: processed-files
    volumes:
      - shared_uploads:/uploads
    depends_on:
      - rabbitmq
      - minio
    networks:
      - backend-network

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    privileged: true
    ports:
      - "8083:8083"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_QUEUE: notification-queue
    depends_on:
      - rabbitmq
    networks:
      - backend-network

  upload-file-gateway:
    build:
      context: ./upload-file-gateway
    container_name: upload-file-gateway
    privileged: true
    ports:
      - "8080:8080"
    depends_on:
      - upload-service
      - processing-service
      - notification-service
    networks:
      - backend-network

volumes:
  minio_data:
  postgres_data:
  rabbitmq_data:
  shared_uploads: