file:
  upload:
    path: ${FILE_UPLOAD_PATH}
spring:
  application:
    name: upload-service
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  datasource:
    url: ${SPRING_JDBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  flyway:
    url: ${SPRING_JDBC_URL}
    user: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    queues:
      processing: ${SPRING_RABBITMQ_QUEUE}
      processed: ${SPRING_RABBITMQ_QUEUE_PROCESSED}
      notification_failure: ${SPRING_RABBITMQ_QUEUE_NOTIFICATION_FAILURE}
    listener:
      simple:
        acknowledge-mode: auto
    template:
      exchange: ${SPRING_RABBITMQ_FILE_PROCESSED_TOPIC_EXCHANGE}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
server:
  port: 8081
